ConnexoProject/force-app/main/default/objects/Security__c/Security__c.object-meta.xml
<CustomObject>
    <description>System Security Requests Module for Trackwise , ValGenesis and Compliance Wire .</description>
    <label>Security</label>
    <nameField>
        <displayFormat>SEC-{000000}</displayFormat>
        <label>Security Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConnexoProject/force-app/main/default/objects/Security__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Modify</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Deactivate</fullName>
                <isActive>false</isActive>
                <label>Deactivate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConnexoProject/force-app/main/default/objects/Security__c/fields/Email_Long__c.field-meta.xml
<CustomField>
    <fullName>Email_Long__c</fullName>
    <description>Use a comma to separate Emails.</description>
    <inlineHelpText>Use a comma to separate Emails.</inlineHelpText>
    <label>Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ConnexoProject/force-app/main/default/objects/Security__c/fields/Functional_Area_Manager__c.field-meta.xml
<CustomField>
    <fullName>Functional_Area_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Functional Area Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Security</relationshipName>
    <type>Lookup</type>
</CustomField>

ConnexoProject/force-app/main/default/objects/Security__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>System__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DMS User</fullName>
            </value>
            <value>
                <fullName>DMS Admin</fullName>
            </value>
            <value>
                <fullName>Pharma Owner</fullName>
            </value>
            <value>
                <fullName>CAPA</fullName>
            </value>
            <value>
                <fullName>Change Control</fullName>
            </value>
            <value>
                <fullName>Quality Events</fullName>
            </value>
            <value>
                <fullName>Complaints</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Observation</fullName>
            </value>
            <value>
                <fullName>Owner Transfer</fullName>
            </value>
            <value>
                <fullName>View Only</fullName>
            </value>
            <value>
                <fullName>Managers and Supervisors</fullName>
            </value>
            <value>
                <fullName>Primary Manager</fullName>
            </value>
            <value>
                <fullName>Learner</fullName>
            </value>
            <value>
                <fullName>Quality Assurance Reporting View</fullName>
            </value>
            <value>
                <fullName>Quality Assurance Documentation Internal</fullName>
            </value>
            <value>
                <fullName>Gowning Verifications</fullName>
            </value>
            <value>
                <fullName>IT Admin</fullName>
            </value>
            <value>
                <fullName>Organization Administrator</fullName>
            </value>
            <value>
                <fullName>Course Owner</fullName>
            </value>
            <value>
                <fullName>General User</fullName>
            </value>
            <value>
                <fullName>Alarm User</fullName>
            </value>
            <value>
                <fullName>Engineering User</fullName>
            </value>
            <value>
                <fullName>Business Administrator</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Non GxP Reviewer</fullName>
            </value>
            <value>
                <fullName>Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Query Administrator</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>IQBO</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConnexoProject/force-app/main/default/objects/Security__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ConnexoProject/force-app/main/default/objects/Security__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <label>System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BMRAM</fullName>
            </value>
            <value>
                <fullName>Facility Access</fullName>
            </value>
            <value>
                <fullName>Image Lab</fullName>
            </value>
            <value>
                <fullName>LabChip</fullName>
            </value>
            <value>
                <fullName>LabVantage</fullName>
            </value>
            <value>
                <fullName>Lighthouse Portable</fullName>
            </value>
            <value>
                <fullName>Ops Autoclave</fullName>
            </value>
            <value>
                <fullName>Ops Bioreactor</fullName>
            </value>
            <value>
                <fullName>Ops FlexiPro</fullName>
            </value>
            <value>
                <fullName>Ops Flowstar</fullName>
            </value>
            <value>
                <fullName>Ops MVP</fullName>
            </value>
            <value>
                <fullName>Ops Nanodrop</fullName>
            </value>
            <value>
                <fullName>OPS ViCell Blu</fullName>
            </value>
            <value>
                <fullName>PLA NanoDrops</fullName>
            </value>
            <value>
                <fullName>PLA XDR Fermenters</fullName>
            </value>
            <value>
                <fullName>QC ddPCRs</fullName>
            </value>
            <value>
                <fullName>QC HPLC</fullName>
            </value>
            <value>
                <fullName>QC Nanodrop</fullName>
            </value>
            <value>
                <fullName>QC Osmometer</fullName>
            </value>
            <value>
                <fullName>QC Plate Readers</fullName>
            </value>
            <value>
                <fullName>QC qPCRs</fullName>
            </value>
            <value>
                <fullName>QC UltraRed</fullName>
            </value>
            <value>
                <fullName>RES_Q</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>Schneider BAS</fullName>
            </value>
            <value>
                <fullName>Tempo</fullName>
            </value>
            <value>
                <fullName>TetraScience</fullName>
            </value>
            <value>
                <fullName>Trackwise</fullName>
            </value>
            <value>
                <fullName>Tulip</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConnexoProject/force-app/main/default/objects/Security__c/fields/Training_Completed__c.field-meta.xml
<CustomField>
    <fullName>Training_Completed__c</fullName>
    <label>Training Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Delayed Verification</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <isActive>false</isActive>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConnexoProject/force-app/main/default/objects/Security__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <description>Use a comma to separate Username.</description>
    <inlineHelpText>Use a comma to separate Username.</inlineHelpText>
    <label>User Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ConnexoProject/force-app/main/default/classes/Security_c_123TriggerTest.cls
/*
*********************************************************
Apex Trigger Name  : Security_c_123Trigger
Object             : Security - Security__c
Created Date       : Feb 22, 2025
@description       : This is test class for Security_c object trigger.
@author            : Amit
Modification Log:
Ver   Date         Author                               Modification
1.0   22-02-2025   Amit			                         Initial Version
*********************************************************
*/

@isTest
public class Security_c_123TriggerTest {
        @testSetup   
        private static void testSetup() {
            List<Security__c> secList = new List<Security__c>();
            for (Integer i = 0; i < 5; i++) {
                Security__c sec = new Security__c(); // Create a new instance inside the loop
                sec.Short_Description__c = 'Test Security ' + i;
                sec.UserName__c = 'test.apex' + i; // Ensure unique UserName__c
                sec.System__c = 'LabChip';
                sec.Role__c = 'User';
                sec.Email_Long__c = '1.1+' + i + '@gmail.com'; // Ensure unique Email_Long__c
                sec.Action__c = 'Add';
                // sec.Functional_Area_Manager__c = 'Admin';
                sec.Training_Completed__c = 'Yes';
                secList.add(sec);
            }
            insert secList;
        }
    
    
        @IsTest    
    	private static void testUpdateCheck() {
        List<Security__c> secUpdateList = new List<Security__c>();
        secUpdateList=[select id,Short_Description__c,System__c,Role__c,Action__c from Security__c limit 5];      
        for(Security__c sec :secUpdateList)
        {
            sec.System__c='SAP';
            sec.Role__c='IQBO';
        }
        update secUpdateList;
        
        List<Security__c>secNewUpdateList=[select id,Short_Description__c,System__c,Role__c,Action__c from Security__c limit 5];
        for(Security__c updatesec :secNewUpdateList)
        {
            system.assertEquals('SAP',updatesec.System__c);
            system.assertEquals('IQBO',updatesec.Role__c);
        }
        
        }
    
    	@IsTest    
    	private static void testDeleteCheck() {
            
        List<Security__c> deleteList = [select id from Security__c limit 5];
            delete deleteList;
            
        List<Security__c> deleteListCheck = [select id from Security__c where id IN :deleteList];
            system.assertEquals(0,deleteListCheck.size());
            
        }
    
    	@IsTest    
    	private static void testUnDeleteCheck() {
            
        List<Security__c> deleteList = [select id from Security__c limit 5];
            delete deleteList;
            Undelete deleteList;
            
        List<Security__c> deleteListCheck = [select id from Security__c where id IN :deleteList];
            system.assertEquals(5,deleteListCheck.size());
            for(Security__c sec : deleteListCheck)
            {
                system.assertNotEquals(null,sec.Id);
            }
        }
}