ConnexoProject/force-app/main/default/objects/Security__c/Security__c.object-meta.xml
<CustomObject>
    <description>System Security Requests Module for Trackwise , ValGenesis and Compliance Wire .</description>
    <label>Security</label>
    <nameField>
        <displayFormat>SEC-{000000}</displayFormat>
        <label>Security Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Security</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ConnexoProject/force-app/main/default/objects/Security__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add</fullName>
            </value>
            <value>
                <fullName>Modify</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Deactivate</fullName>
                <isActive>false</isActive>
                <label>Deactivate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ConnexoProject/force-app/main/default/objects/Security__c/fields/CMPL123Task_Key_Value__c.field-meta.xml
<CustomField>
    <fullName>CMPL123Task_Key_Value__c</fullName>
    <label>Task Field Update Key Value</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

ConnexoProject/force-app/main/default/classes/TWDSecurityBatchUpdate.cls
/*
*********************************************************
Apex Trigger Name  : Security_c_123Trigger
Object             : Security - Security__c
Created Date       : Feb 22, 2025
@description       : This is batch class for Security_c object to fetch all records where state is Training Verification and action field with value 'Remove'.The identified records 
					CMPL123Task_Key_Value__c is updated to 123 task value 'remove'.
@author            : Amit
Modification Log:
Ver   Date         Author                               Modification
1.0   22-02-2025   Amit			                         Initial Version
*********************************************************
*/

global class TWDSecurityBatchUpdate implements Database.Batchable<SObject> {
        
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Id FROM Security__c 
            WHERE Action__c = 'remove'  
            AND CMPL123_WF_Status__c = 'Process Owner Review']);
    }
    
    global void execute(Database.BatchableContext BC, List<Security__c> scope) {
        for (Security__c sec : scope) {
            sec.CMPL123Task_Key_Value__c = 'remove';
        }
        update scope;
    }
    
    global void finish(Database.BatchableContext BC) {
        System.debug('Batch Process Completed.');
    }
}